# Change these first
owner: naoTimesdev # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: "naoTimes [bot]"
    url: $BOT_PING_IP
    port: $BOT_PING_PORT
    check: "tcp-ping"
    icon: https://naoti.me/img/favicon.ico
  - name: "naoTimes [web/docs]"
    url: https://naoti.me/
    icon: https://naoti.me/img/favicon.ico
  - name: "naoTimes [webui]"
    url: https://panel.naoti.me/
    icon: https://naoti.me/img/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.naoti.me
  # baseUrl: /your-repo-name
  logoUrl: https://naoti.me/assets/img/nt192.png
  name: naoTimes Status
  theme: ocean
  favicon: https://naoti.me/img/favicon.ico

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
